(SELECT CONCAT('Podium: ',team) AS name FROM LEAGUE ORDER BY POSITION
LIMIT 3)
UNION ALL 
(WITH t AS (SELECT * FROM LEAGUE ORDER BY position DESC LIMIT 2)
  SELECT CONCAT('Demoted: ',team) FROM t ORDER BY position ASC);